### ISSUE TITLE
下载了你的莫言小说训练demo。用tensorflow训练了下。

### ISSUE THREAD

**Issue by thebesttome** [audier/my_deep_project#1]
每次训练完成。直接跑测试。效果和你的微博里面的效果一样。有句子。。
但是我注释掉训练的代码。直接用你的原生测试代码跑。。。每次出来的都是
如题：
酬满骇踏演频演踏踏郑踏郑踏郑踏踏踏踏呵郑呵郑踏培培呵呵茄亢亢亢亢呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵
这种杂乱无章的句子。
求大佬详解

**Comment by thebesttome** [comment]
下载了你的代码。用tensorflow训练了下。定义网络层级为3层，512节点和作者跑出来的一样。。但是没改动任何代码的情况下。注释掉模型训练的代码。其他任何代码没动过。在预测出来的结果是：酬满骇踏演频演踏踏郑踏郑踏郑踏踏踏踏呵郑呵郑踏培培呵呵茄亢亢亢亢呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵。。测试10次。都是这样。每次不注释训练模型的代码。跑50次。出来的第一次结果是对的。然后注释模型训练的代码。在预测。。始终不对。作者这是什么原因了

**Comment by audier** [comment]
你好，我自己测试一下哈

**Comment by audier** [comment]
你好，那个字典需要保存定死，不能重新生成，重新生成顺序会改变，当时我也没注意。。。就像跑一下看看就行。。。

**Comment by audier** [comment]
你可以debug一下，哈哈

**Comment by audier** [comment]
解决了告诉我

**Comment by thebesttome** [comment]
感谢作者。。debug了下。。测试了下。。确实每次字典不一样了。我晚上编译在试试

**Comment by audier** [comment]
你好，我弄了个n-gram模型作为对照，你可以看看效果。
https://github.com/audier/my_deep_project/blob/master/NLP/1.moyan_novel/ngram_test.ipynb

**Comment by thebesttome** [comment]
好的。。感谢作者。。
